# The URL the site will be built for
base_url = "https://jbial.github.io"

# The site title and description

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [{ name = "tags" }]

theme = "archie-zola"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
# control dark mode: auto | dark | toggle
mode = "toggle"

# subtitle will show under the title in index page
subtitle = "A zola theme forked from [archie](https://github.com/athul/archie)"

# if set true, will use external CDN resource to load font and js file
useCDN = false

favicon = "/icon/black.png"

# show in the footer
copyright = "Jeff"

# config your Google Analysis ID
ga = "XXXX-XXXXX"

# config multi-language menu and other text
[[extra.translations.en]]
show_more = "Read more ⟶"
previous_page = "← Previous"
next_page = "Next →"
posted_on = "on "
posted_by = "Published by"
read_time = "minute read"
all_tags = "All tags"

menus = [
    { name = "Home", url = "/" },
    { name = "Posts", url = "/posts" },
    { name = "Research", url = "/research" },
]

# config social icon info in the footer
[[extra.social]]
icon = "github"
name = "GitHub"
url = "https://github.com/jbial"

[[extra.social]]
icon = "twitter"
name = "Twitter"
url = "https://x.com/bialjail"

katex_enable = true
